require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rake

AllCops:
  NewCops: enable

Layout/LineLength:
  Exclude:
    - spec/**/*

RSpec/DescribeClass:
  Exclude:
    - spec/features/**/*

RSpec/ExampleLength:
  Exclude:
    - spec/**/*

RSpec/MultipleExpectations:
  Exclude:
    - spec/features/**/*

RSpec/Capybara/FeatureMethods:
  EnabledMethods:
    - feature
    - scenario

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/StringLiterals:
  EnforcedStyle: double_quotes
